version: '3'

volumes:
  postgres_data:
    driver: local

services:

#============================#
#==========POSTGRES==========#
#============================#
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: noccures
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'

#============================#
#==========KEYCLOAK==========#
#============================#
#  keycloak:
#    image: quay.io/keycloak/keycloak:19.0.1
#    environment:
#      DB_VENDOR: POSTGRES
#      DB_ADDR: postgres
#      DB_DATABASE: keycloak
#      DB_USER: keycloak
#      DB_SCHEMA: public
#      DB_PASSWORD: password
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    ports:
#      - "8180:8080"
#    depends_on:
#      - postgres
#    command:
#      - start-dev
#    volumes:
#      - .local/keycloak/:/opt/jboss/keycloak/standalone/data/
