version: '3'

volumes:
  postgres_data:
    driver: local

services:
#============================#
#==========POSTGRES==========#
#============================#
  postgres-dev:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: noccures
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'

#==================================#
#==========POSTGRES-TESTS==========#
#==================================#
  postgres-tests:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '5433:5432'
