version: '3'

services:

#============================#
#==========SONARQUBE=========#
#============================#
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - postgres-sonar
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5434/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"


#============================#
#=======POSTGRES-SONAR=======#
#============================#
  postgres-sonar:
    image: postgres
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql_sonar:/var/lib/postgresql
      - postgresql_data_sonar:/var/lib/postgresql/data
    ports:
      - "5434:5434"

#============================#
#========POSTGRES-DEV========#
#============================#
  postgres-dev:
    image: postgres
    volumes:
      - ./docker/postgres_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: noccures
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'

#==================================#
#==========POSTGRES-TESTS==========#
#==================================#
  postgres-tests:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '5433:5432'


#==================================#
#==========VOLUME-MAPPING==========#
#==================================#
volumes:
  postgres_data:
    driver: local
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_sonar:
  postgresql_data_sonar:
